### ISSUE TITLE
[CLOSED] Rewrite of AlternateDataStream support.

### ISSUE THREAD

**Issue by alphaleonis** [alphaleonis/AlphaFS.New#59]
_Issue by **[alphaleonis](https://github.com/alphaleonis)** from Saturday Jan 10, 2015 at 19:37 GMT_
_Originally opened as https://github.com/alphaleonis/AlphaFS/pull/59_

----

Completely rewrote the Alternate Data Stream support. It now utilizes FindFirstStream/FindNextStream to enumerate streams, since the method of using the BackupRead-functions enumerates more than the data streams, and also it cannot enumerate the data streams of an encrypted file. 

Removed support for adding/removing streams. This can already be done via normal file functions, so no additional functions is needed for this.  It is furthermore a rarely used operation, so to maintain a bunch of convenience methods for this seems unnecessary.

----

_**[alphaleonis](https://github.com/alphaleonis)** included the following code: https://github.com/alphaleonis/AlphaFS/pull/59/commits_

**Comment by mgaruccio** [comment]
Sorry for asking what is probably an obvious question but how can I add an alternate data stream to a file with a path name longer than NTFS supports without the addstream method in the AlphaFS library?  you mention normal file functions but everything I've tried gives me a path too long error.
